-- ===========================================================
-- mooket_db schema initialization (regenerated from production)
-- 
-- Usage:
--   psql -U <user> -d <db> -f schema.sql
-- 
-- Generated by .tmp/parse_schema.py from pg_dump --schema-only
-- ===========================================================

-- Preamble: server settings (safe defaults, won't affect existing sessions)
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- ===== FUNCTIONS =====
-- ----- clean_expired_offers -----
--
-- Name: clean_expired_offers(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.clean_expired_offers() RETURNS void
    LANGUAGE plpgsql
    AS $$
BEGIN
    DELETE FROM biz_offer WHERE data_date < CURRENT_DATE - INTERVAL '2 days';
END;
$$;
--
-- Name: FUNCTION clean_expired_offers(); Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON FUNCTION public.clean_expired_offers() IS '清理过期报盘数据（保留最近2天）';

-- ----- update_merchant_stat -----
--
-- Name: update_merchant_stat(integer, date); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_merchant_stat(merchant_id_param integer, stat_date_param date) RETURNS void
    LANGUAGE plpgsql
    AS $$
BEGIN
    INSERT INTO stat_merchant (stat_date, merchant_id, today_offer_count, today_inquiry_count, today_product_count, today_factory_count, update_time)
    SELECT
        stat_date_param,
        merchant_id_param,
        COUNT(*) FILTER (WHERE offer_type = '报盘') as offer_count,
        COUNT(*) FILTER (WHERE offer_type = '求购') as inquiry_count,
        COUNT(DISTINCT product_id) FILTER (WHERE offer_type = '报盘') as product_count,
        COUNT(DISTINCT factory_id) FILTER (WHERE offer_type = '报盘' AND factory_id IS NOT NULL) as factory_count,
        CURRENT_TIMESTAMP
    FROM biz_offer
    WHERE merchant_id = merchant_id_param
      AND data_date = stat_date_param
      AND status = 'ACTIVE'
    GROUP BY merchant_id
    ON CONFLICT (stat_date, merchant_id) DO UPDATE SET
        today_offer_count = EXCLUDED.today_offer_count,
        today_inquiry_count = EXCLUDED.today_inquiry_count,
        today_product_count = EXCLUDED.today_product_count,
        today_factory_count = EXCLUDED.today_factory_count,
        update_time = CURRENT_TIMESTAMP;
END;
$$;
--
-- Name: FUNCTION update_merchant_stat(merchant_id_param integer, stat_date_param date); Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON FUNCTION public.update_merchant_stat(merchant_id_param integer, stat_date_param date) IS '更新商家统计数据';

-- ===== TABLES (in dependency order) =====
-- ----- 01. dict_user -----
--
-- Name: dict_user_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.dict_user_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: dict_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dict_user (
    user_id bigint NOT NULL,
    phone character varying(20) NOT NULL,
    nickname character varying(20),
    identity_tags character varying(200),
    wechat character varying(50),
    wechat_nickname character varying(50),
    real_name character varying(50),
    create_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    avatar_url character varying(500),
    real_name_status character varying(20) DEFAULT 'pending'::character varying,
    cancellation_status character varying(20) DEFAULT 'active'::character varying,
    mooket_id character varying(50),
    mooket_no character varying(100)
);

--
-- Name: dict_user_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.dict_user_user_id_seq OWNED BY public.dict_user.user_id;

--
-- Name: dict_user user_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dict_user ALTER COLUMN user_id SET DEFAULT nextval('public.dict_user_user_id_seq'::regclass);

--
-- Name: dict_user dict_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dict_user
    ADD CONSTRAINT dict_user_pkey PRIMARY KEY (user_id);

--
-- Name: idx_dict_user_phone; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dict_user_phone ON public.dict_user USING btree (phone);


-- ----- 02. dict_product -----
--
-- Name: dict_product_product_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.dict_product_product_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: dict_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dict_product (
    product_id integer NOT NULL,
    category character varying(10) NOT NULL,
    product_name character varying(100) NOT NULL,
    alias_list character varying(500) DEFAULT ''::character varying,
    create_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    source_goods_id bigint
);

--
-- Name: dict_product_product_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.dict_product_product_id_seq OWNED BY public.dict_product.product_id;

--
-- Name: dict_product product_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dict_product ALTER COLUMN product_id SET DEFAULT nextval('public.dict_product_product_id_seq'::regclass);

--
-- Name: dict_product dict_product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dict_product
    ADD CONSTRAINT dict_product_pkey PRIMARY KEY (product_id);
--
-- Name: dict_product uk_category_product; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dict_product
    ADD CONSTRAINT uk_category_product UNIQUE (category, product_name);

--
-- Name: idx_dict_product_source_goods_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dict_product_source_goods_id ON public.dict_product USING btree (source_goods_id);
--
-- Name: idx_product_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_product_category ON public.dict_product USING btree (category);
--
-- Name: idx_product_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_product_name ON public.dict_product USING btree (product_name);
--
-- Name: uk_dict_product_source_goods_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_dict_product_source_goods_id ON public.dict_product USING btree (source_goods_id) WHERE (source_goods_id IS NOT NULL);


-- ----- 03. dict_product_source_map -----
--
-- Name: dict_product_source_map; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dict_product_source_map (
    source_goods_id bigint NOT NULL,
    product_id integer NOT NULL,
    create_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

--
-- Name: dict_product_source_map dict_product_source_map_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dict_product_source_map
    ADD CONSTRAINT dict_product_source_map_pkey PRIMARY KEY (source_goods_id);

--
-- Name: idx_dict_product_source_map_product_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dict_product_source_map_product_id ON public.dict_product_source_map USING btree (product_id);


-- ----- 04. dict_factory -----
--
-- Name: dict_factory_factory_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.dict_factory_factory_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: dict_factory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dict_factory (
    factory_id integer NOT NULL,
    category character varying(10) NOT NULL,
    country character varying(50) NOT NULL,
    country_alias character varying(200) DEFAULT ''::character varying,
    factory_no character varying(50) NOT NULL,
    brand_id integer,
    create_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

--
-- Name: dict_factory_factory_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.dict_factory_factory_id_seq OWNED BY public.dict_factory.factory_id;

--
-- Name: dict_factory factory_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dict_factory ALTER COLUMN factory_id SET DEFAULT nextval('public.dict_factory_factory_id_seq'::regclass);

--
-- Name: dict_factory dict_factory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dict_factory
    ADD CONSTRAINT dict_factory_pkey PRIMARY KEY (factory_id);
--
-- Name: dict_factory uk_category_country_factory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dict_factory
    ADD CONSTRAINT uk_category_country_factory UNIQUE (category, country, factory_no);

--
-- Name: idx_factory_brand; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_factory_brand ON public.dict_factory USING btree (brand_id);
--
-- Name: idx_factory_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_factory_category ON public.dict_factory USING btree (category);
--
-- Name: idx_factory_country; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_factory_country ON public.dict_factory USING btree (country);
--
-- Name: idx_factory_no; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_factory_no ON public.dict_factory USING btree (factory_no);


-- ----- 05. dict_brand -----
--
-- Name: dict_brand_brand_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.dict_brand_brand_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: dict_brand; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dict_brand (
    brand_id integer NOT NULL,
    brand_name character varying(100) NOT NULL,
    alias_list character varying(500) DEFAULT ''::character varying,
    create_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    factory_id integer,
    factory_no character varying(100),
    country character varying(50),
    category character varying(20)
);

--
-- Name: dict_brand_brand_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.dict_brand_brand_id_seq OWNED BY public.dict_brand.brand_id;

--
-- Name: dict_brand brand_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dict_brand ALTER COLUMN brand_id SET DEFAULT nextval('public.dict_brand_brand_id_seq'::regclass);

--
-- Name: dict_brand dict_brand_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dict_brand
    ADD CONSTRAINT dict_brand_pkey PRIMARY KEY (brand_id);

--
-- Name: idx_brand_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_brand_name ON public.dict_brand USING btree (brand_name);


-- ----- 06. dict_merchant -----
--
-- Name: dict_merchant_merchant_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.dict_merchant_merchant_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: dict_merchant; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dict_merchant (
    merchant_id bigint NOT NULL,
    merchant_name character varying(200) NOT NULL,
    merchant_short_name character varying(100) DEFAULT ''::character varying,
    merchant_tags character varying(200) DEFAULT ''::character varying,
    contact_phone character varying(20) DEFAULT ''::character varying,
    create_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

--
-- Name: dict_merchant_merchant_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.dict_merchant_merchant_id_seq OWNED BY public.dict_merchant.merchant_id;

--
-- Name: dict_merchant merchant_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dict_merchant ALTER COLUMN merchant_id SET DEFAULT nextval('public.dict_merchant_merchant_id_seq'::regclass);

--
-- Name: dict_merchant dict_merchant_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dict_merchant
    ADD CONSTRAINT dict_merchant_pkey PRIMARY KEY (merchant_id);

--
-- Name: idx_merchant_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_merchant_name ON public.dict_merchant USING btree (merchant_name);


-- ----- 07. factory_tier -----
--
-- Name: factory_tier_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.factory_tier_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: factory_tier; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.factory_tier (
    id integer NOT NULL,
    category character varying(20) DEFAULT '牛'::character varying,
    product_name character varying(100) NOT NULL,
    factory_no character varying(50) NOT NULL,
    tier character varying(10) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    country character varying(50) DEFAULT '巴西'::character varying
);

--
-- Name: factory_tier_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.factory_tier_id_seq OWNED BY public.factory_tier.id;

--
-- Name: factory_tier id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factory_tier ALTER COLUMN id SET DEFAULT nextval('public.factory_tier_id_seq'::regclass);

--
-- Name: factory_tier factory_tier_country_product_name_factory_no_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factory_tier
    ADD CONSTRAINT factory_tier_country_product_name_factory_no_key UNIQUE (country, product_name, factory_no, tier);
--
-- Name: factory_tier factory_tier_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.factory_tier
    ADD CONSTRAINT factory_tier_pkey PRIMARY KEY (id);

--
-- Name: idx_factory_tier_tier; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_factory_tier_tier ON public.factory_tier USING btree (category, product_name, tier);


-- ----- 08. rel_user_merchant -----
--
-- Name: rel_user_merchant; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rel_user_merchant (
    user_id bigint NOT NULL,
    mobile character varying(20) DEFAULT ''::character varying,
    nickname character varying(100) DEFAULT ''::character varying,
    identity character varying(200) DEFAULT ''::character varying,
    merchant_id bigint,
    create_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

--
-- Name: rel_user_merchant rel_user_merchant_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rel_user_merchant
    ADD CONSTRAINT rel_user_merchant_pkey PRIMARY KEY (user_id);

--
-- Name: idx_user_merchant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_merchant ON public.rel_user_merchant USING btree (merchant_id);
--
-- Name: idx_user_mobile; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_mobile ON public.rel_user_merchant USING btree (mobile);


-- ----- 09. biz_offer -----
--
-- Name: biz_offer_offer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.biz_offer_offer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: biz_offer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.biz_offer (
    offer_id bigint NOT NULL,
    offer_original_text text DEFAULT ''::text,
    category character varying(10) NOT NULL,
    product_id integer,
    product_name character varying(100) NOT NULL,
    country character varying(50) DEFAULT ''::character varying,
    factory_no character varying(50) DEFAULT ''::character varying,
    factory_id integer,
    brand_id integer,
    merchant_id bigint,
    contact_phone character varying(20) DEFAULT ''::character varying,
    user_id bigint NOT NULL,
    user_nickname character varying(100) DEFAULT ''::character varying,
    price numeric(10,2) DEFAULT NULL::numeric,
    price_max numeric(10,2) DEFAULT NULL::numeric,
    weight character varying(50) DEFAULT ''::character varying,
    offer_type character varying(10) NOT NULL,
    goods_type character varying(20) DEFAULT ''::character varying,
    goods_location character varying(50) DEFAULT ''::character varying,
    tags character varying(200) DEFAULT ''::character varying,
    fat_ratio character varying(20) DEFAULT ''::character varying,
    feeding_type character varying(20) DEFAULT ''::character varying,
    cattle_breed character varying(50) DEFAULT ''::character varying,
    remark text DEFAULT ''::text,
    publish_time timestamp without time zone NOT NULL,
    data_date date NOT NULL,
    status character varying(20) DEFAULT 'ACTIVE'::character varying,
    create_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    package_id character varying,
    package_price numeric(12,2),
    package_total_quantity character varying,
    package_sell_type character varying,
    source_business_id bigint
);

--
-- Name: biz_offer_offer_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.biz_offer_offer_id_seq OWNED BY public.biz_offer.offer_id;

--
-- Name: biz_offer offer_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.biz_offer ALTER COLUMN offer_id SET DEFAULT nextval('public.biz_offer_offer_id_seq'::regclass);

--
-- Name: biz_offer biz_offer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.biz_offer
    ADD CONSTRAINT biz_offer_pkey PRIMARY KEY (offer_id);

--
-- Name: idx_biz_offer_group_agg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_biz_offer_group_agg ON public.biz_offer USING btree (product_id, category, offer_type, status, data_date, country, factory_no);
--
-- Name: idx_biz_offer_product_query; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_biz_offer_product_query ON public.biz_offer USING btree (product_id, category, offer_type, status, data_date);
--
-- Name: idx_biz_offer_source_business_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_biz_offer_source_business_id ON public.biz_offer USING btree (source_business_id);
--
-- Name: idx_offer_brand; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_offer_brand ON public.biz_offer USING btree (brand_id);
--
-- Name: idx_offer_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_offer_category ON public.biz_offer USING btree (category);
--
-- Name: idx_offer_data_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_offer_data_date ON public.biz_offer USING btree (data_date);
--
-- Name: idx_offer_factory; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_offer_factory ON public.biz_offer USING btree (factory_id);
--
-- Name: idx_offer_feeding_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_offer_feeding_type ON public.biz_offer USING btree (feeding_type);
--
-- Name: idx_offer_goods_location; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_offer_goods_location ON public.biz_offer USING btree (goods_location);
--
-- Name: idx_offer_goods_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_offer_goods_type ON public.biz_offer USING btree (goods_type);
--
-- Name: idx_offer_merchant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_offer_merchant ON public.biz_offer USING btree (merchant_id);
--
-- Name: idx_offer_product; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_offer_product ON public.biz_offer USING btree (product_id);
--
-- Name: idx_offer_publish_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_offer_publish_time ON public.biz_offer USING btree (publish_time);
--
-- Name: idx_offer_search; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_offer_search ON public.biz_offer USING btree (category, offer_type, status, data_date);
--
-- Name: idx_offer_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_offer_status ON public.biz_offer USING btree (status);
--
-- Name: idx_offer_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_offer_type ON public.biz_offer USING btree (offer_type);
--
-- Name: uk_biz_offer_source_business_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_biz_offer_source_business_id ON public.biz_offer USING btree (source_business_id);


-- ----- 10. biz_search_history -----
--
-- Name: biz_search_history_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.biz_search_history_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: biz_search_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.biz_search_history (
    history_id bigint NOT NULL,
    user_id bigint NOT NULL,
    search_word character varying(200) NOT NULL,
    search_type character varying(50) NOT NULL,
    is_self_select smallint DEFAULT 0,
    create_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    product_id bigint,
    product_name character varying(255),
    country character varying(100),
    factory_no character varying(100),
    brand_id bigint,
    merchant_id bigint
);

--
-- Name: biz_search_history_history_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.biz_search_history_history_id_seq OWNED BY public.biz_search_history.history_id;

--
-- Name: biz_search_history history_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.biz_search_history ALTER COLUMN history_id SET DEFAULT nextval('public.biz_search_history_history_id_seq'::regclass);

--
-- Name: biz_search_history biz_search_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.biz_search_history
    ADD CONSTRAINT biz_search_history_pkey PRIMARY KEY (history_id);

--
-- Name: idx_search_history_create_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_search_history_create_time ON public.biz_search_history USING btree (user_id, create_time DESC);
--
-- Name: idx_search_history_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_search_history_user ON public.biz_search_history USING btree (user_id);
--
-- Name: idx_search_history_user_select; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_search_history_user_select ON public.biz_search_history USING btree (user_id, is_self_select);

--
-- Name: TABLE biz_search_history; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.biz_search_history IS '搜索历史表';
--
-- Name: COLUMN biz_search_history.history_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.biz_search_history.history_id IS '历史ID，主键';
--
-- Name: COLUMN biz_search_history.user_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.biz_search_history.user_id IS '用户ID';
--
-- Name: COLUMN biz_search_history.search_word; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.biz_search_history.search_word IS '搜索词';
--
-- Name: COLUMN biz_search_history.search_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.biz_search_history.search_type IS '搜索类型';
--
-- Name: COLUMN biz_search_history.is_self_select; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.biz_search_history.is_self_select IS '是否自选（0-否，1-是）';
--
-- Name: COLUMN biz_search_history.create_time; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.biz_search_history.create_time IS '创建时间';

-- ----- 11. stat_country -----
--
-- Name: stat_country_stat_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.stat_country_stat_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: stat_country; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stat_country (
    stat_id integer NOT NULL,
    stat_date date NOT NULL,
    category character varying(20) NOT NULL,
    country character varying(50) NOT NULL,
    today_offer_count integer DEFAULT 0,
    today_inquiry_count integer DEFAULT 0,
    today_factory_count integer DEFAULT 0,
    today_merchant_count integer DEFAULT 0,
    update_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    hot_factories text,
    hot_products text
);

--
-- Name: stat_country_stat_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.stat_country_stat_id_seq OWNED BY public.stat_country.stat_id;

--
-- Name: stat_country stat_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_country ALTER COLUMN stat_id SET DEFAULT nextval('public.stat_country_stat_id_seq'::regclass);

--
-- Name: stat_country stat_country_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_country
    ADD CONSTRAINT stat_country_pkey PRIMARY KEY (stat_date, country, category);
--
-- Name: stat_country uk_stat_country_date_country_category; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_country
    ADD CONSTRAINT uk_stat_country_date_country_category UNIQUE (stat_date, country, category);

--
-- Name: idx_stat_country_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stat_country_date ON public.stat_country USING btree (stat_date);
--
-- Name: idx_stat_country_offer_count; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stat_country_offer_count ON public.stat_country USING btree (stat_date, today_offer_count DESC);

--
-- Name: TABLE stat_country; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.stat_country IS '国家维度统计表';
--
-- Name: COLUMN stat_country.stat_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_country.stat_date IS '统计日期';
--
-- Name: COLUMN stat_country.category; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_country.category IS '大类：牛/猪';
--
-- Name: COLUMN stat_country.country; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_country.country IS '国家';
--
-- Name: COLUMN stat_country.today_offer_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_country.today_offer_count IS '今日报盘数';
--
-- Name: COLUMN stat_country.today_inquiry_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_country.today_inquiry_count IS '今日求购数';
--
-- Name: COLUMN stat_country.today_factory_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_country.today_factory_count IS '今日活跃厂号数';
--
-- Name: COLUMN stat_country.today_merchant_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_country.today_merchant_count IS '今日报盘商家数';

-- ----- 12. stat_factory -----
--
-- Name: stat_factory_stat_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.stat_factory_stat_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: stat_factory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stat_factory (
    stat_id integer NOT NULL,
    stat_date date NOT NULL,
    category character varying(20) NOT NULL,
    country character varying(50) NOT NULL,
    factory_no character varying(50) NOT NULL,
    factory_id integer NOT NULL,
    today_offer_count integer DEFAULT 0,
    today_inquiry_count integer DEFAULT 0,
    today_merchant_count integer DEFAULT 0,
    price_min numeric(10,2),
    price_max numeric(10,2),
    update_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

--
-- Name: stat_factory_stat_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.stat_factory_stat_id_seq OWNED BY public.stat_factory.stat_id;

--
-- Name: stat_factory stat_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_factory ALTER COLUMN stat_id SET DEFAULT nextval('public.stat_factory_stat_id_seq'::regclass);

--
-- Name: stat_factory pk_stat_factory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_factory
    ADD CONSTRAINT pk_stat_factory PRIMARY KEY (stat_date, factory_id, category);

--
-- Name: idx_stat_factory_offer_count; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stat_factory_offer_count ON public.stat_factory USING btree (stat_date, today_offer_count DESC);

--
-- Name: TABLE stat_factory; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.stat_factory IS '国家厂号维度统计表';
--
-- Name: COLUMN stat_factory.stat_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory.stat_date IS '统计日期';
--
-- Name: COLUMN stat_factory.category; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory.category IS '大类：牛/猪';
--
-- Name: COLUMN stat_factory.country; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory.country IS '国家';
--
-- Name: COLUMN stat_factory.factory_no; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory.factory_no IS '厂号';
--
-- Name: COLUMN stat_factory.factory_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory.factory_id IS '厂号ID';
--
-- Name: COLUMN stat_factory.today_offer_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory.today_offer_count IS '今日报盘数';
--
-- Name: COLUMN stat_factory.today_inquiry_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory.today_inquiry_count IS '今日求购数';
--
-- Name: COLUMN stat_factory.today_merchant_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory.today_merchant_count IS '今日报盘商家数';
--
-- Name: COLUMN stat_factory.price_min; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory.price_min IS '今日最低价';
--
-- Name: COLUMN stat_factory.price_max; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory.price_max IS '今日最高价';

-- ----- 13. stat_product -----
--
-- Name: stat_product_stat_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.stat_product_stat_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: stat_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stat_product (
    stat_id integer NOT NULL,
    stat_date date NOT NULL,
    category character varying(20) NOT NULL,
    product_id integer NOT NULL,
    product_name character varying(100) NOT NULL,
    today_offer_count integer DEFAULT 0,
    today_inquiry_count integer DEFAULT 0,
    today_merchant_count integer DEFAULT 0,
    today_factory_count integer DEFAULT 0,
    price_min numeric(10,2),
    price_max numeric(10,2),
    update_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

--
-- Name: stat_product_stat_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.stat_product_stat_id_seq OWNED BY public.stat_product.stat_id;

--
-- Name: stat_product stat_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_product ALTER COLUMN stat_id SET DEFAULT nextval('public.stat_product_stat_id_seq'::regclass);

--
-- Name: stat_product pk_stat_product; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_product
    ADD CONSTRAINT pk_stat_product PRIMARY KEY (stat_date, product_id);

--
-- Name: idx_stat_product_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stat_product_date ON public.stat_product USING btree (stat_date);
--
-- Name: idx_stat_product_offer_count; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stat_product_offer_count ON public.stat_product USING btree (stat_date, today_offer_count DESC);

--
-- Name: TABLE stat_product; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.stat_product IS '产品维度统计表';
--
-- Name: COLUMN stat_product.stat_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_product.stat_date IS '统计日期';
--
-- Name: COLUMN stat_product.category; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_product.category IS '大类：牛/猪';
--
-- Name: COLUMN stat_product.product_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_product.product_id IS '产品ID';
--
-- Name: COLUMN stat_product.product_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_product.product_name IS '产品名称';
--
-- Name: COLUMN stat_product.today_offer_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_product.today_offer_count IS '今日报盘数';
--
-- Name: COLUMN stat_product.today_inquiry_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_product.today_inquiry_count IS '今日求购数';
--
-- Name: COLUMN stat_product.today_merchant_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_product.today_merchant_count IS '今日报盘商家数';
--
-- Name: COLUMN stat_product.today_factory_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_product.today_factory_count IS '今日报盘工厂数';
--
-- Name: COLUMN stat_product.price_min; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_product.price_min IS '今日最低价';
--
-- Name: COLUMN stat_product.price_max; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_product.price_max IS '今日最高价';

-- ----- 14. stat_merchant -----
--
-- Name: stat_merchant_stat_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.stat_merchant_stat_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: stat_merchant; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stat_merchant (
    stat_id integer NOT NULL,
    stat_date date NOT NULL,
    merchant_id bigint NOT NULL,
    today_offer_count integer DEFAULT 0,
    today_inquiry_count integer DEFAULT 0,
    today_product_count integer DEFAULT 0,
    today_factory_count integer DEFAULT 0,
    update_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    category character varying(20) DEFAULT '牛'::character varying NOT NULL
);

--
-- Name: stat_merchant_stat_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.stat_merchant_stat_id_seq OWNED BY public.stat_merchant.stat_id;

--
-- Name: stat_merchant stat_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_merchant ALTER COLUMN stat_id SET DEFAULT nextval('public.stat_merchant_stat_id_seq'::regclass);

--
-- Name: stat_merchant stat_merchant_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_merchant
    ADD CONSTRAINT stat_merchant_pkey PRIMARY KEY (stat_date, merchant_id, category);
--
-- Name: stat_merchant uk_stat_date_merchant; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_merchant
    ADD CONSTRAINT uk_stat_date_merchant UNIQUE (stat_date, merchant_id, category);
--
-- Name: stat_merchant uk_stat_date_merchant_category; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_merchant
    ADD CONSTRAINT uk_stat_date_merchant_category UNIQUE (stat_date, merchant_id, category);

--
-- Name: idx_stat_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stat_date ON public.stat_merchant USING btree (stat_date);
--
-- Name: idx_stat_merchant_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stat_merchant_date ON public.stat_merchant USING btree (stat_date);
--
-- Name: idx_stat_merchant_date_merchant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stat_merchant_date_merchant ON public.stat_merchant USING btree (stat_date, merchant_id, category);
--
-- Name: idx_stat_merchant_merchant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stat_merchant_merchant ON public.stat_merchant USING btree (merchant_id);


-- ----- 15. stat_brand -----
--
-- Name: stat_brand_stat_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.stat_brand_stat_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: stat_brand; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stat_brand (
    stat_id integer NOT NULL,
    stat_date date NOT NULL,
    brand_id integer NOT NULL,
    brand_name character varying(100) NOT NULL,
    today_offer_count integer DEFAULT 0,
    today_factory_count integer DEFAULT 0,
    today_product_count integer DEFAULT 0,
    price_min numeric(10,2),
    price_max numeric(10,2),
    update_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    category character varying(20) DEFAULT '牛'::character varying NOT NULL
);

--
-- Name: stat_brand_stat_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.stat_brand_stat_id_seq OWNED BY public.stat_brand.stat_id;

--
-- Name: stat_brand stat_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_brand ALTER COLUMN stat_id SET DEFAULT nextval('public.stat_brand_stat_id_seq'::regclass);

--
-- Name: stat_brand pk_stat_brand; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_brand
    ADD CONSTRAINT pk_stat_brand PRIMARY KEY (stat_date, brand_id, category);

--
-- Name: TABLE stat_brand; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.stat_brand IS '品牌维度统计表';
--
-- Name: COLUMN stat_brand.stat_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_brand.stat_date IS '统计日期';
--
-- Name: COLUMN stat_brand.brand_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_brand.brand_id IS '品牌ID';
--
-- Name: COLUMN stat_brand.brand_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_brand.brand_name IS '品牌名称';
--
-- Name: COLUMN stat_brand.today_offer_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_brand.today_offer_count IS '今日报盘数';
--
-- Name: COLUMN stat_brand.today_factory_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_brand.today_factory_count IS '今日报盘工厂数';
--
-- Name: COLUMN stat_brand.today_product_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_brand.today_product_count IS '今日报盘产品种类数';
--
-- Name: COLUMN stat_brand.price_min; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_brand.price_min IS '今日最低价';
--
-- Name: COLUMN stat_brand.price_max; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_brand.price_max IS '今日最高价';

-- ----- 16. stat_country_product -----
--
-- Name: stat_country_product_stat_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.stat_country_product_stat_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: stat_country_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stat_country_product (
    stat_id integer NOT NULL,
    stat_date date NOT NULL,
    category character varying(20) NOT NULL,
    country character varying(50) NOT NULL,
    product_id integer NOT NULL,
    product_name character varying(100) NOT NULL,
    today_offer_count integer DEFAULT 0,
    today_factory_count integer DEFAULT 0,
    price_min numeric(10,2),
    price_max numeric(10,2),
    avg_price numeric(10,2),
    avg_price_yesterday numeric(10,2),
    price_change numeric(10,2),
    price_change_rate numeric(5,2),
    update_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    today_inquiry_count integer DEFAULT 0
);

--
-- Name: stat_country_product_stat_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.stat_country_product_stat_id_seq OWNED BY public.stat_country_product.stat_id;

--
-- Name: stat_country_product stat_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_country_product ALTER COLUMN stat_id SET DEFAULT nextval('public.stat_country_product_stat_id_seq'::regclass);

--
-- Name: stat_country_product pk_stat_country_product; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_country_product
    ADD CONSTRAINT pk_stat_country_product PRIMARY KEY (stat_date, country, product_id, category);

--
-- Name: idx_stat_country_product_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stat_country_product_date ON public.stat_country_product USING btree (stat_date);
--
-- Name: idx_stat_country_product_offer_count; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stat_country_product_offer_count ON public.stat_country_product USING btree (stat_date, today_offer_count DESC);

--
-- Name: TABLE stat_country_product; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.stat_country_product IS '国家产品维度统计表';
--
-- Name: COLUMN stat_country_product.stat_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_country_product.stat_date IS '统计日期';
--
-- Name: COLUMN stat_country_product.category; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_country_product.category IS '大类：牛/猪';
--
-- Name: COLUMN stat_country_product.country; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_country_product.country IS '国家';
--
-- Name: COLUMN stat_country_product.product_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_country_product.product_id IS '产品ID';
--
-- Name: COLUMN stat_country_product.product_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_country_product.product_name IS '产品名称';
--
-- Name: COLUMN stat_country_product.today_offer_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_country_product.today_offer_count IS '今日报盘数';
--
-- Name: COLUMN stat_country_product.today_factory_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_country_product.today_factory_count IS '今日报盘工厂数';
--
-- Name: COLUMN stat_country_product.price_min; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_country_product.price_min IS '今日最低价';
--
-- Name: COLUMN stat_country_product.price_max; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_country_product.price_max IS '今日最高价';
--
-- Name: COLUMN stat_country_product.avg_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_country_product.avg_price IS '今日均价';
--
-- Name: COLUMN stat_country_product.avg_price_yesterday; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_country_product.avg_price_yesterday IS '昨日均价';
--
-- Name: COLUMN stat_country_product.price_change; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_country_product.price_change IS '涨跌额';
--
-- Name: COLUMN stat_country_product.price_change_rate; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_country_product.price_change_rate IS '涨跌幅（%）';

-- ----- 17. stat_factory_product -----
--
-- Name: stat_factory_product_stat_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.stat_factory_product_stat_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: stat_factory_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stat_factory_product (
    stat_id integer NOT NULL,
    stat_date date NOT NULL,
    factory_id integer NOT NULL,
    factory_no character varying(50) NOT NULL,
    country character varying(50) NOT NULL,
    product_id integer NOT NULL,
    product_name character varying(100) NOT NULL,
    today_offer_count integer DEFAULT 0,
    today_inquiry_count integer DEFAULT 0,
    price_min numeric(10,2),
    price_max numeric(10,2),
    avg_price numeric(10,2),
    avg_price_yesterday numeric(10,2),
    price_change numeric(10,2),
    price_change_rate numeric(10,2),
    update_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    category character varying(20) DEFAULT '牛'::character varying NOT NULL
);

--
-- Name: stat_factory_product_stat_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.stat_factory_product_stat_id_seq OWNED BY public.stat_factory_product.stat_id;

--
-- Name: stat_factory_product stat_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_factory_product ALTER COLUMN stat_id SET DEFAULT nextval('public.stat_factory_product_stat_id_seq'::regclass);

--
-- Name: stat_factory_product pk_stat_factory_product; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_factory_product
    ADD CONSTRAINT pk_stat_factory_product PRIMARY KEY (stat_date, factory_id, product_id, category);

--
-- Name: TABLE stat_factory_product; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.stat_factory_product IS '国家厂号产品维度统计表';
--
-- Name: COLUMN stat_factory_product.stat_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory_product.stat_date IS '统计日期';
--
-- Name: COLUMN stat_factory_product.factory_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory_product.factory_id IS '厂号ID';
--
-- Name: COLUMN stat_factory_product.factory_no; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory_product.factory_no IS '厂号';
--
-- Name: COLUMN stat_factory_product.country; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory_product.country IS '国家';
--
-- Name: COLUMN stat_factory_product.product_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory_product.product_id IS '产品ID';
--
-- Name: COLUMN stat_factory_product.product_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory_product.product_name IS '产品名称';
--
-- Name: COLUMN stat_factory_product.today_offer_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory_product.today_offer_count IS '今日报盘数';
--
-- Name: COLUMN stat_factory_product.today_inquiry_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory_product.today_inquiry_count IS '今日求购数';
--
-- Name: COLUMN stat_factory_product.price_min; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory_product.price_min IS '今日最低价';
--
-- Name: COLUMN stat_factory_product.price_max; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory_product.price_max IS '今日最高价';
--
-- Name: COLUMN stat_factory_product.avg_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory_product.avg_price IS '今日均价';
--
-- Name: COLUMN stat_factory_product.avg_price_yesterday; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory_product.avg_price_yesterday IS '昨日均价';
--
-- Name: COLUMN stat_factory_product.price_change; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory_product.price_change IS '涨跌额';
--
-- Name: COLUMN stat_factory_product.price_change_rate; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_factory_product.price_change_rate IS '涨跌幅（%）';

-- ----- 18. stat_brand_product -----
--
-- Name: stat_brand_product_stat_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.stat_brand_product_stat_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: stat_brand_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stat_brand_product (
    stat_id integer NOT NULL,
    stat_date date NOT NULL,
    brand_id integer NOT NULL,
    brand_name character varying(100) NOT NULL,
    product_id integer NOT NULL,
    product_name character varying(100) NOT NULL,
    today_factory_count integer DEFAULT 0,
    today_offer_count integer DEFAULT 0,
    price_min numeric(10,2),
    price_max numeric(10,2),
    avg_price numeric(10,2),
    avg_price_yesterday numeric(10,2),
    price_change numeric(10,2),
    price_change_rate numeric(10,2),
    update_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    category character varying(10) DEFAULT '牛'::character varying NOT NULL
);

--
-- Name: stat_brand_product_stat_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.stat_brand_product_stat_id_seq OWNED BY public.stat_brand_product.stat_id;

--
-- Name: stat_brand_product stat_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_brand_product ALTER COLUMN stat_id SET DEFAULT nextval('public.stat_brand_product_stat_id_seq'::regclass);

--
-- Name: stat_brand_product pk_stat_brand_product; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_brand_product
    ADD CONSTRAINT pk_stat_brand_product PRIMARY KEY (stat_date, brand_id, product_id, category);

--
-- Name: idx_stat_brand_product_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stat_brand_product_date ON public.stat_brand_product USING btree (stat_date);
--
-- Name: idx_stat_brand_product_offer_count; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stat_brand_product_offer_count ON public.stat_brand_product USING btree (stat_date, today_offer_count DESC);
--
-- Name: idx_stat_brand_product_pk; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_stat_brand_product_pk ON public.stat_brand_product USING btree (stat_date, brand_id, product_id, category);

--
-- Name: TABLE stat_brand_product; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.stat_brand_product IS '品牌产品维度统计表';
--
-- Name: COLUMN stat_brand_product.stat_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_brand_product.stat_date IS '统计日期';
--
-- Name: COLUMN stat_brand_product.brand_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_brand_product.brand_id IS '品牌ID';
--
-- Name: COLUMN stat_brand_product.brand_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_brand_product.brand_name IS '品牌名称';
--
-- Name: COLUMN stat_brand_product.product_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_brand_product.product_id IS '产品ID';
--
-- Name: COLUMN stat_brand_product.product_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_brand_product.product_name IS '产品名称';
--
-- Name: COLUMN stat_brand_product.today_factory_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_brand_product.today_factory_count IS '今日报盘工厂数';
--
-- Name: COLUMN stat_brand_product.today_offer_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_brand_product.today_offer_count IS '今日报盘数';
--
-- Name: COLUMN stat_brand_product.price_min; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_brand_product.price_min IS '今日最低价';
--
-- Name: COLUMN stat_brand_product.price_max; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_brand_product.price_max IS '今日最高价';
--
-- Name: COLUMN stat_brand_product.avg_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_brand_product.avg_price IS '今日均价';
--
-- Name: COLUMN stat_brand_product.avg_price_yesterday; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_brand_product.avg_price_yesterday IS '昨日均价';
--
-- Name: COLUMN stat_brand_product.price_change; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_brand_product.price_change IS '涨跌额';
--
-- Name: COLUMN stat_brand_product.price_change_rate; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.stat_brand_product.price_change_rate IS '涨跌幅（%）';

-- ----- 19. stat_price_trend -----
--
-- Name: stat_price_trend_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.stat_price_trend_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: stat_price_trend; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stat_price_trend (
    id bigint NOT NULL,
    stat_date date NOT NULL,
    dimension_type character varying(50) NOT NULL,
    country character varying(100),
    product_id integer,
    product_name character varying(200),
    factory_no character varying(100),
    offer_type character varying(20),
    avg_price numeric(10,2),
    record_date date NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

--
-- Name: stat_price_trend_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.stat_price_trend_id_seq OWNED BY public.stat_price_trend.id;

--
-- Name: stat_price_trend id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_price_trend ALTER COLUMN id SET DEFAULT nextval('public.stat_price_trend_id_seq'::regclass);

--
-- Name: stat_price_trend stat_price_trend_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_price_trend
    ADD CONSTRAINT stat_price_trend_pkey PRIMARY KEY (id);
--
-- Name: stat_price_trend stat_price_trend_stat_date_dimension_type_country_product_i_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stat_price_trend
    ADD CONSTRAINT stat_price_trend_stat_date_dimension_type_country_product_i_key UNIQUE (stat_date, dimension_type, country, product_id, factory_no, offer_type);

--
-- Name: idx_trend_query; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trend_query ON public.stat_price_trend USING btree (dimension_type, country, product_id, factory_no, offer_type, stat_date DESC);
--
-- Name: idx_trend_record; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trend_record ON public.stat_price_trend USING btree (dimension_type, country, product_id, factory_no, offer_type, record_date);

