-- Update dict_brand based on Excel 集团vs厂号.xlsx
-- Generated by Claude Code

BEGIN;

-- Step 1: Create temp table with Excel data
DROP TABLE IF EXISTS tmp_excel_brand;
CREATE TEMP TABLE tmp_excel_brand (
    factory_no VARCHAR(50),
    brand_name VARCHAR(255),
    alias_list VARCHAR(255)
);

INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF1110', 'JBS', '金佰顺');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF112', 'Rio Maria', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF1206', 'Frigorifico Sul', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF1251', 'Astra', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF1365', 'Naturafrig', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF1440', 'Iguatemi', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF1662', 'JBS', '金佰顺');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF1751', 'Minerva', '美利华、美丽华');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF177', 'Frima', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF1811', 'Naturafrig', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF1900', 'Minerva', '美利华、美丽华');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF1925', 'Better Beef', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF1940', 'Minerva', '美利华、美丽华');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF2007', 'Minerva', '美利华、美丽华');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF2015', 'Marfrig', 'MF');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF2051', 'Frigol', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF2058', 'JBS', '金佰顺');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF232', 'Minerva', '美利华、美丽华');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF2437', 'Masterboi', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF2443', 'Frigon', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF2471', 'Minerva', '美利华、美丽华');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF2543', 'Marfrig', 'MF');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF2782', 'Bolivia', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF2872', 'Beauvallet', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF2880', 'JBS', '金佰顺');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF2924', 'Frigoestrela', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF3000', 'JBS', '金佰顺');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF3112', 'Frima', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF3181', 'JBS', '金佰顺');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF3215', 'Plena', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF3225', 'JBS', '金佰顺');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF337', 'JBS', '金佰顺');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF3470', 'JBS', '金佰顺');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF385', 'JBS', '金佰顺');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF3941', 'Arga', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF3974', 'Naturafrig', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF4029', 'Frima', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF411', 'Redentor', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF42', 'JBS', '金佰顺');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF421', 'Minerva', '美利华、美丽华');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF4238', 'Minerva', '美利华、美丽华');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF4267', 'Bolivia', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF4302', 'JBS', '金佰顺');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF431', 'Minerva', '美利华、美丽华');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF4333', 'JBS', '金佰顺');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF4398', 'Redentor', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF4400', 'JBS', '金佰顺');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF4413', 'Mercurio', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF4490', 'Vale Grande', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF4554', 'Mercurio', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF457', 'JBS', '金佰顺');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF4695', 'Bolivia', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF504', 'JBS', '金佰顺');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF506', 'Frisa', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF51', 'JBS', '金佰顺');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF5125', 'Boa Carne', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF791', 'Minerva', '美利华、美丽华');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF847', 'Minerva', '美利华、美丽华');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF889', 'Frigorifico Sul', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF93', 'Cooperfrigu', '');
INSERT INTO tmp_excel_brand (factory_no, brand_name, alias_list) VALUES ('SIF941', 'Barra Mansa', '');

-- Step 2: Update dict_brand for factories that ARE in Excel
UPDATE dict_brand db
SET brand_name = te.brand_name,
    alias_list = te.alias_list
FROM tmp_excel_brand te
JOIN dict_factory df ON db.factory_id = df.factory_id
WHERE te.factory_no = df.factory_no;

-- Step 3: Delete dict_brand records for factories NOT in Excel
DELETE FROM dict_brand db
WHERE NOT EXISTS (
    SELECT 1 FROM tmp_excel_brand te
    JOIN dict_factory df ON db.factory_id = df.factory_id
    WHERE te.factory_no = df.factory_no
);

COMMIT;